version: "3"
services:
  db:
    env_file: ./.env
    image: 'mongo'
    restart: 'unless-stopped'
    volumes:
      - ./db:/data/db
    expose:
      - 27017
    ports:
      - "8457:27017"
  web:
    env_file: ./.env
    container_name: 'millie'
    build: './web'
    ports:
      - '8080:3000'
    restart: 'unless-stopped'
    volumes:
      - ./web/src:/app/src
